--
-- MIGRATION CHANGE COLUMN REMARKS TO SINGANTURE AND ADD COLUMN REMARKS TO TABLE JOB
-- 

ALTER TABLE wellac."Job"
RENAME COLUMN remarks TO signature;

ALTER TABLE wellac."Job"
ADD remarks TEXT; 

