worker_processes      1;

error_log  /dev/stderr warn;
pid        /tmp/nginx.pid;

events {
  worker_connections  1024;
}

http {
  # need to remap as non-root user
  client_body_temp_path /tmp/client_temp;
  proxy_temp_path       /tmp/proxy_temp_path;
  fastcgi_temp_path     /tmp/fastcgi_temp;
  uwsgi_temp_path       /tmp/uwsgi_temp;
  scgi_temp_path        /tmp/scgi_temp;

  # logs
  log_format  default '$http_x_forwarded_for $remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_cookie"';

  access_log  /dev/stdout default;

  # hide version information
  server_tokens off;

  # Upload files setting
  sendfile              off;
  client_max_body_size  50M;

  ## Configuration to mitigate "slow HTTP DoS attach"; see OSWAP security explanation
  ## Timeouts in seconds.
  client_body_timeout     10;
  client_header_timeout   95;                ## see: https://sigopt.com/blog/the-case-of-the-mysterious-aws-elb-504-errors/
  send_timeout            10;
  large_client_header_buffers 4 16k;

  # we keep opened connections with browsers 30s
  # It's quite long (3s on a good apache conf) but, hey,
  # this is Nginx and we do not suffer from auto-DOS with
  # limited connections management
  keepalive_timeout   60;

  # mime types scope
  include          /etc/nginx/mime.types;
  default_type     application/octet-stream;

  # gzip compression
  include          /etc/nginx/common/rules.gzip.conf;

  # security headers
  include         /etc/nginx/common/rules.headers.security.conf;

  # closed connections optimisation
  # avoid massive amounts of FIN_WAIT1
  reset_timedout_connection on;

  # TCP options.
  # start sending content when you have it, in small chunks
  tcp_nodelay         on;
  # Optimization of socket handling when using sendfile.
  tcp_nopush          on;

  server {
    # Non-root user canot listen to port below 1000
    listen       8080;

    location /api {
      include /etc/nginx/common/rules.headers.proxy.conf;

      proxy_ignore_client_abort on;

      proxy_pass http://internal-alb-simplify-dev-app-simplify-999933903.ap-southeast-1.elb.amazonaws.com/api;
    }
  }
}
