--
-- Update Default Value Email templates
--

DO $$DECLARE r record;
BEGIN
    FOR r IN SELECT LOWER(key) as name FROM "shared"."Tenant"
    LOOP
        IF (SELECT EXISTS(SELECT 1 FROM information_schema.schemata WHERE schema_name = r.name)) THEN
            EXECUTE 
            'UPDATE '|| r.name ||'."TableColumnSetting" SET "column" = ''[{"field":"id","name":"Quotation Title & ID","isVisible":true,"isDisabled":true, "sort":true},{"field":"serviceAddress","name":"Service Address","isVisible":true,"isDisabled":false, "sort": false},{"field":"term","name":"Quotation Term","isVisible":true,"isDisabled":false, "sort":true},{"field":"contractType","name":"Quotation Type","isVisible":true,"isDisabled":true, "sort": false},{"field":"contractStatus","name":"Quotation Status","isVisible":true,"isDisabled":false, "sort": false},{"field":"contractProgress","name":"Quotation Progress","isVisible":true,"isDisabled":false, "sort": false},{"field":"invoiceNo","name":"Invoice Number","isVisible":true,"isDisabled":true, "sort": false},{"field":"contractAmount","name":"Quotation Amount","isVisible":true,"isDisabled":true, "sort": false},{"field":"collectedAmount","name":"Collected Amount","isVisible":true,"isDisabled":false, "sort":false}]'' WHERE id=2;
             UPDATE '|| r.name ||'."TableColumnSetting" SET "column" = ''[{"field":"id","name":"ID","isVisible":true,"isDisabled":true, "sort":true}, {"field":"contract","name":"Quotation & Invoice","isVisible":true,"isDisabled":false, "sort": false}, {"field":"serviceAddress","name":"Service Address","isVisible":true,"isDisabled":true, "sort":true},{"field":"jobStatus","name":"Job Status","isVisible":true,"isDisabled":true, "sort": false},{"field":"startDateTime","name":"Start Date & Time","isVisible":true,"isDisabled":true, "sort":true},{"field":"serviceType","name":"Job Type","isVisible":true,"isDisabled":false, "sort": false}, {"field":"jobAmount","name":"Job Amount","isVisible":true,"isDisabled":false, "sort": false}, {"field":"collectedAmount","name":"Collected Amount","isVisible":true,"isDisabled":false, "sort": false}, {"field":"paymentMethod","name":"Payment Method","isVisible":true,"isDisabled":false, "sort": false}, {"field":"vehicleNo","name":"Vehicle","isVisible":true,"isDisabled":false, "sort": false}, {"field":"employee","name":"Employee","isVisible":true,"isDisabled":false, "sort": false}, {"field":"jobLabels","name":"Job Labels","isVisible":true,"isDisabled":false, "sort":false}]'' WHERE id=3;
             UPDATE '|| r.name ||'."TableColumnSetting" SET "column" = ''[{"field":"id","name":"Quotation Title & ID","isVisible":true,"isDisabled":true, "sort":true},{"field":"clientName","name":"Client & Entity Name","isVisible":true,"isDisabled":true, "sort": false},{"field":"serviceAddress","name":"Service Address","isVisible":true,"isDisabled":false, "sort": false},{"field":"term","name":"Quotation Term","isVisible":true,"isDisabled":false, "sort":true},{"field":"contractType","name":"Quotation Type","isVisible":true,"isDisabled":true, "sort": false},{"field":"contractStatus","name":"Quotation Status","isVisible":true,"isDisabled":false, "sort": false},{"field":"contractProgress","name":"Quotation Progress","isVisible":true,"isDisabled":false, "sort": false},{"field":"invoiceNo","name":"Invoice Number","isVisible":true,"isDisabled":true, "sort": false},{"field":"contractAmount","name":"Quotation Amount","isVisible":true,"isDisabled":true, "sort": false},{"field":"collectedAmount","name":"Collected Amount","isVisible":true,"isDisabled":false, "sort":false}]'' WHERE id=4;
             UPDATE '|| r.name ||'."TableColumnSetting" SET "column" = ''[{"field":"id","name":"ID & Job Sequence","isVisible":true,"isDisabled":true,"sort":true}, {"field":"clientName","name":"Client Name","isVisible":true,"isDisabled":true,"sort":true}, {"field":"contract","name":"Quotation & Invoice","isVisible":true,"isDisabled":false,"sort":false}, {"field":"serviceAddress","name":"Service Address","isVisible":true,"isDisabled":true,"sort":false}, {"field":"startDateTime","name":"Start Date & Time","isVisible":true,"isDisabled":true,"sort":true}, {"field":"serviceType","name":"Job Type","isVisible":true,"isDisabled":false,"sort": false}, {"field":"jobAmount","name":"Job Amount","isVisible":true,"isDisabled":false,"sort": false}, {"field":"collectedAmount","name":"Collected Amount","isVisible":true,"isDisabled":false,"sort": false}, {"field":"paymentMethod","name":"Payment Method","isVisible":true,"isDisabled":false,"sort": false}, {"field":"vehicleNo","name":"Vehicle","isVisible":true,"isDisabled":false,"sort": false}, {"field":"employee","name":"Employee","isVisible":true,"isDisabled":false,"sort": false}, {"field":"jobLabels","name":"Job Labels","isVisible":true,"isDisabled":false,"sort":false}]'' WHERE id=6;';
        END IF;
    END LOOP;
END$$;
