import User from '../models/User';
import UserProfile from '../models/UserProfile';
import Role from '../models/Role';
import Permission from '../models/Permission';
import ModelBase from '../models/ModelBase';
import Client from '../models/Client';
import ServiceAddress from '../models/ServiceAddress';
import ServiceItemTemplate from '../models/ServiceItemTemplate';
import Service from '../models/Service';
import ServiceItem from '../models/ServiceItem';
import ServiceSkill from '../models/ServiceSkill';
import Schedule from '../models/Schedule';
import Job from '../models/Job';
import JobNote from '../models/JobNote';
import JobDocument from '../models/JobDocument';
import JobExpenses from '../models/JobExpenses';
import JobExpensesItem from '../models/JobExpensesItem';
import JobHistory from '../models/JobHistory';
import Tenant from '../models/Tenant';
import Vehicle from '../models/Vehicle';
import Entity from '../models/Entity';
import Invoice from '../models/Invoice';
import ServiceTemplate from '../models/ServiceTemplate';
import SkillTemplate from '../models/SkillTemplate';
import UserSkill from '../models/UserSkill';
import ChecklistTemplate from '../models/ChecklistTemplate';
import ChecklistItemTemplate from '../models/ChecklistItemTemplate';
import ChecklistJob from '../models/ChecklistJob';
import ChecklistJobItem from '../models/ChecklistJobItem';
import Setting from '../models/Setting';
import TableColumnSetting from '../models/TableColumnSetting';
import AppLog from '../models/AppLog';
import Agent from '../models/Agent';
import ContactPerson from '../models/ContactPerson';
import Rating from '../models/Rating';
import JobNoteTemplate from '../models/JobNoteTemplate';
import Equipment from '../models/Equipment';
import JobLabelTemplate from '../models/JobLabelTemplate';
import JobLabel from '../models/JobLabel';
import WaJob from '../models/WaJob';
import Notification from '../models/Notification';
import BrandTemplate from '../models/BrandTemplate';
import ClientDocument from '../models/ClientDocument';
import GstTemplate from '../models/GstTemplate';
import InvoiceHistory from '../models/InvoiceHistory';
import CollectedAmountHistory from '../models/CollectedAmountHistory';
import JobNoteMedia from '../models/JobNoteMedia';
import CustomField from '../models/CustomField';
import TimeOff from '../models/TimeOff';
import District from '../models/District';
import RoleGrant from '../models/RoleGrant';
import PdfTemplateOptions from '../models/PdfTemplateOptions';
import BookingSetting from '../models/BookingSetting';

export interface Models {
  Tenant: typeof Tenant;
  User: typeof User;
  UserProfile: typeof UserProfile;
  Role: typeof Role;
  Permission: typeof Permission;
  Client: typeof Client;
  ServiceAddress: typeof ServiceAddress;
  ServiceItemTemplate: typeof ServiceItemTemplate;
  Service: typeof Service;
  ServiceItem: typeof ServiceItem;
  ServiceSkill: typeof ServiceSkill;
  Schedule: typeof Schedule;
  Job: typeof Job;
  JobNote: typeof JobNote;
  JobDocument: typeof JobDocument;
  JobExpenses: typeof JobExpenses;
  JobExpensesItem: typeof JobExpensesItem;
  JobHistory: typeof JobHistory;
  Vehicle: typeof Vehicle;
  Entity: typeof Entity;
  Invoice: typeof Invoice;
  ServiceTemplate: typeof ServiceTemplate;
  SkillTemplate: typeof SkillTemplate;
  UserSkill: typeof UserSkill;
  ChecklistTemplate: typeof ChecklistTemplate;
  ChecklistItemTemplate: typeof ChecklistItemTemplate;
  ChecklistJob: typeof ChecklistJob;
  ChecklistJobItem: typeof ChecklistJobItem;
  Setting: typeof Setting;
  TableColumnSetting: typeof TableColumnSetting;
  AppLog: typeof AppLog;
  Agent: typeof Agent;
  ContactPerson: typeof ContactPerson;
  Rating: typeof Rating;
  JobNoteTemplate: typeof JobNoteTemplate;
  Equipment: typeof Equipment;
  JobLabelTemplate: typeof JobLabelTemplate;
  JobLabel: typeof JobLabel;
  WaJob: typeof WaJob;
  Notification: typeof Notification;
  BrandTemplate: typeof BrandTemplate;
  ClientDocument: typeof ClientDocument;
  GstTemplate: typeof GstTemplate;
  InvoiceHistory: typeof InvoiceHistory;
  CollectedAmountHistory: typeof CollectedAmountHistory;
  JobNoteMedia: typeof JobNoteMedia;
  CustomField: typeof CustomField;
  TimeOff: typeof TimeOff;
  District: typeof District;
  RoleGrant: typeof RoleGrant;
  PdfTemplateOptions: typeof PdfTemplateOptions;
  BookingSetting: typeof BookingSetting;
  [key: string]: typeof ModelBase;
}
